title: Home
views:
  - title: Home
    path: default_view
    badges: []
    cards:

      - type: entities
        entities:
          - entity: input_number.input_number_1

      - type: 'custom:animated-consumption-card'
        entity: input_number.input_number_1
        left_icon: mdi:flash
        right_icon: mdi:ceiling-light
        show_line: true

      - type: entities
        entities:
          - entity: input_number.input_number_2

      - type: 'custom:animated-consumption-card'
        entity: input_number.input_number_2
        circle_color: black

      - type: 'custom:animated-consumption-card'

      - type: 'custom:animated-consumption-card'
        entity: sun.sun

  - title: aaa
    path: aaa
    badges: []
    cards:
      - type: 'custom:animated-consumption-card'
        entity: sensor.total_power_consumption
      - type: entities
        entities:
          - entity: input_boolean.lamp
            name: Lamp (100 W)
          - entity: input_boolean.heater1
            name: Heater (1 kW)
          - entity: input_boolean.heater2
            name: Heater (1 kW)
        show_header_toggle: false
